#!/bin/bash
g++ -mno-cygwin \
	-DPY_ARRAY_UNIQUE_SYMBOL=zarg \
	-DNO_IMPORT_ARRAY \
	standalone_test.c \
	DX9Sound.cpp \
	SoundRecord.cpp \
	pydsound_pyd.cpp \
	-I/drive/c/Python25/include \
	-I/drive/c/Python25/Lib/site-packages/numpy/core/include \
	-L/drive/c/Python25/libs -lpython25 \
	2>&1| less -S

#	-I/drive/c/DX90SDK/Include \
#	-L/drive/c/DX90SDK/Lib -ldsound -DDYNAMIC_DSOUND=0 \

# ryota also linked to dxguid and winmm
