/*
 * This file is generated by numpycoresetup.pyc. DO NOT EDIT 
 */
#define NPY_SIZEOF_SHORT 2 
#define NPY_SIZEOF_INT 4 
#define NPY_SIZEOF_LONG 4 
#define NPY_SIZEOF_FLOAT 4 
#define NPY_SIZEOF_DOUBLE 8 
#define NPY_SIZEOF_LONGDOUBLE 12 
#define NPY_SIZEOF_PY_INTPTR_T 4 

#define NPY_NO_SIGNAL
#define NPY_NO_SMP 0

#define NPY_SIZEOF_LONGLONG 8 
#define NPY_SIZEOF_PY_LONG_LONG 8 
/* #define CHAR_BIT 8 */
