// Import declarations for gMOBIlabPlus.h, generated by dylib_imports.sh
#ifndef gMOBIlabPlus_IMPORTS_H
#define gMOBIlabPlus_IMPORTS_H

#include "Win32Defs.h"

#if DYNAMIC_IMPORTS
#define GT_OpenDevice GT_OpenDevice_306c
#define GT_CloseDevice GT_CloseDevice_e5f9
#define GT_SetDigitalOut GT_SetDigitalOut_ce16
#define GT_InitChannels GT_InitChannels_4e30
#define GT_StartAcquisition GT_StartAcquisition_f5dd
#define GT_StopAcquisition GT_StopAcquisition_411f
#define GT_GetData GT_GetData_c54e
#define GT_GetConfig GT_GetConfig_b2ed
#define GT_SetFilename GT_SetFilename_3832
#define GT_PauseXfer GT_PauseXfer_f8d3
#define GT_ResumeXfer GT_ResumeXfer_2efa
#define GT_EnableSDcard GT_EnableSDcard_1874
#define GT_GetDeviceStatus GT_GetDeviceStatus_0d97
#define GT_GetSDcardStatus GT_GetSDcardStatus_9e8b
#define GT_SetTestmode GT_SetTestmode_6625
#define GT_GetDriverVersion GT_GetDriverVersion_89e5
#define GT_GetLastError GT_GetLastError_bc18
#define GT_TranslateErrorCode GT_TranslateErrorCode_4796
#endif // DYNAMIC_IMPORTS

#include "gMOBIlabPlus.h"

#if DYNAMIC_IMPORTS
#undef GT_OpenDevice
#undef GT_CloseDevice
#undef GT_SetDigitalOut
#undef GT_InitChannels
#undef GT_StartAcquisition
#undef GT_StopAcquisition
#undef GT_GetData
#undef GT_GetConfig
#undef GT_SetFilename
#undef GT_PauseXfer
#undef GT_ResumeXfer
#undef GT_EnableSDcard
#undef GT_GetDeviceStatus
#undef GT_GetSDcardStatus
#undef GT_SetTestmode
#undef GT_GetDriverVersion
#undef GT_GetLastError
#undef GT_TranslateErrorCode

extern "C" {
extern HANDLE (__stdcall *GT_OpenDevice)(LPSTR lpPort);
extern BOOL (__stdcall *GT_CloseDevice)(HANDLE hDevice);
extern BOOL (__stdcall *GT_SetDigitalOut)(HANDLE hDevice, UCHAR dout);
extern BOOL (__stdcall *GT_InitChannels)(HANDLE hDevice,_AIN analogCh,_DIO digitalCh);
extern BOOL (__stdcall *GT_StartAcquisition)(HANDLE hDevice);
extern BOOL (__stdcall *GT_StopAcquisition)(HANDLE hDevice);
extern BOOL (__stdcall *GT_GetData)(HANDLE hDevice,_BUFFER_ST *buffer,LPOVERLAPPED lpOvl);
extern BOOL (__stdcall *GT_GetConfig)(HANDLE hdevice, __CFG * cfg);
extern BOOL (__stdcall *GT_SetFilename)(HANDLE hDevice, LPSTR FileName, int length);
extern BOOL (__stdcall *GT_PauseXfer)(HANDLE hDevice);
extern BOOL (__stdcall *GT_ResumeXfer)(HANDLE hDevice);
extern BOOL (__stdcall *GT_EnableSDcard)(HANDLE hDevice, BOOL enSDcard);
extern BOOL (__stdcall *GT_GetDeviceStatus)(HANDLE hDevice, __DEVICESTATE * DevState);
extern BOOL (__stdcall *GT_GetSDcardStatus)(HANDLE hDevice, UINT * SDStatus);
extern BOOL (__stdcall *GT_SetTestmode)(HANDLE hDevice, BOOL Testmode);
extern float (__stdcall *GT_GetDriverVersion)();
extern BOOL (__stdcall *GT_GetLastError)(UINT * LastError);
extern BOOL (__stdcall *GT_TranslateErrorCode)(_ERRSTR *ErrorString, UINT ErrorCode);
}
#endif // DYNAMIC_IMPORTS

namespace Dylib { bool gMOBIlabPlus_Loaded(); }

#endif // gMOBIlabPlus_IMPORTS_H
