#!/bin/bash
# 
# Usage
# 
#      ./gbuild [OPTS] ../../../shared/modules/CoreModule.cpp
#                  compile one or more named modules if not already up-to-date
#
#      ./gbuild [OPTS]
#                  compile all non-up-to-date sources and (if all successful) link
# 
#      Options:
#         -l       do not compile: just print whether or not module would be compiled
#         -r       recompile even if apparently up-to-date

CPP="g++"
CPPFLAGS="-DMODTYPE=3 -DDYNAMIC_PYTHON=1"

LD="g++"
LDFLAGS=""

SHARED="../../../../shared"
OBJDIR="obj"
OUTDIR="../../demo/prog"
OUTNAME="PythonApplication"

LIBS_POSIX="-lrt -ldl"
LIBS_WIN32="-lws2_32"

INCS="\
../shared \
$SHARED \
$SHARED/accessors \
$SHARED/bcistream \
$SHARED/config \
$SHARED/fileio \
$SHARED/modules \
$SHARED/types \
$SHARED/utils \
$SHARED/utils/Expression \
"


SRC="\
PythonApplication.cpp \
../shared/PythonFilter.cpp \
../shared/PythonLink24.cpp \
../shared/PythonLink25.cpp \
../shared/PythonLink26.cpp \
../shared/PythonWrapper.cpp \
$SHARED/accessors/BCIEvent.cpp \
$SHARED/accessors/Environment.cpp \
$SHARED/accessors/ParamRef.cpp \
$SHARED/bcistream/BCIError.cpp \
$SHARED/bcistream/BCIError_module.cpp \
$SHARED/fileio/BCIDirectory.cpp \
$SHARED/modules/CoreModule.cpp \
$SHARED/modules/GenericFilter.cpp \
$SHARED/modules/MessageHandler.cpp \
$SHARED/types/BitmapImage.cpp \
$SHARED/types/Brackets.cpp \
$SHARED/types/Color.cpp \
$SHARED/types/EncodedString.cpp \
$SHARED/types/GenericSignal.cpp \
$SHARED/types/GenericVisualization.cpp \
$SHARED/types/HierarchicalLabel.cpp \
$SHARED/types/LabelIndex.cpp \
$SHARED/types/Param.cpp \
$SHARED/types/ParamList.cpp \
$SHARED/types/PhysicalUnit.cpp \
$SHARED/types/SignalProperties.cpp \
$SHARED/types/SignalType.cpp \
$SHARED/types/State.cpp \
$SHARED/types/StateList.cpp \
$SHARED/types/StateVector.cpp \
$SHARED/types/StateVectorSample.cpp \
$SHARED/types/Status.cpp \
$SHARED/types/SysCommand.cpp \
$SHARED/utils/ClassName.cpp \
$SHARED/utils/EventQueue.cpp \
$SHARED/utils/Expression/ArithmeticExpression.cpp \
$SHARED/utils/Expression/Expression.cpp \
$SHARED/utils/Expression/ExpressionParser.cpp \
$SHARED/utils/MeasurementUnits.cpp \
$SHARED/utils/OSError.cpp \
$SHARED/utils/PrecisionTime.cpp \
$SHARED/utils/SockStream.cpp \
$SHARED/utils/VersionInfo.cpp \
"

. ../shared/gbuild-pyprep # extra BCPy2000-specific fiddling before calling gbuild-bci2000
. "$SHARED/../contrib/BCPy2000/foundation/shared/gbuild-bci2000"  # general-purpose script for building BCI2000 modules with gcc, managed as part of the BCPy2000 project

